# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 简记
subtitle: 简于形，记于心
description: 凡是过去，皆为序曲
keywords:
author: 月洒清辉映海棠
language: zh-CN
timezone:

# sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://moonbegonia.xyz
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: CNAME

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 0
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:MoonBegonia/MoonBegonia.github.io.git
  branch: master

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  # enable: false
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: live2d-widget-model-haruto # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
  display:
    position: left
    width: 100
    height: 200
    #hOffset: 
    #vOffset: 
  mobile:
    show: false
    scale: 0.3

#字数及阅读时长统计
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true

# ----------------------------------------------------------------
#
# 主题配置
#
#-----------------------------------------------------------------

theme_config:

  # ---------------------------------------------------------------
  # Site Information Settings
  # ---------------------------------------------------------------

  favicon: 
    small: /images/favicon.ico
    medium: /images/favicon.ico
    apple_touch_icon: /images/favicon.ico
    safari_pinned_tab: /images/favicon.ico
    #android_manifest: /images/manifest.json
    #ms_browserconfig: /images/browserconfig.xml

  rss: atom.xml

  footer:
    # Specify the date when the site was setup.
    # If not defined, current year will be used.
    since: 2018

    # Icon between year and copyright info.
    icon:
      # Icon name in fontawesome, see: https://fontawesome.com/v4.7.0/icons
      # `heart` is recommended with animation in red (#ff0000).
      name: heartbeat
      # If you want to animate the icon, set it to true.
      animated: false
      # Change the color of icon, using Hex Code.
      color: "#ff0000"

    # If not defined, will be used `author` from Hexo main config.
    copyright:
    # -------------------------------------------------------------
    powered:
      # Hexo link (Powered by Hexo).
      enable: true
      # Version info of Hexo after Hexo link (vX.X.X).
      version: true

    theme:
      # Theme & scheme info link (Theme - NexT.scheme).
      enable: true
      # Version info of NexT after scheme info (vX.X.X).
      version: true

  creative_commons:
    license: by-nc-sa
    sidebar: true
    post: true

  # ---------------------------------------------------------------
  # SEO Settings
  # ---------------------------------------------------------------

  # Canonical, set a canonical link tag in your hexo, you could use it for your SEO of blog.
  # See: https://support.google.com/webmasters/answer/139066
  # Tips: Before you open this tag, remember set up your URL in hexo _config.yml ( ex. url: http://yourdomain.com )
  canonical: true

  # Change headers hierarchy on site-subtitle (will be main site description) and on all post/pages titles for better SEO-optimization.
  seo: true

  # If true, will add site-subtitle to index page, added in main hexo config.
  # subtitle: Subtitle
  index_with_subtitle: true

  # Automatically add external URL with BASE64 encrypt & decrypt.
  exturl: false

  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  menu:
    home: / || home
    #about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  # Enable/Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: false

  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------

  # Schemes
  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini

  # ---------------------------------------------------------------
  # Sidebar Settings
  # ---------------------------------------------------------------

  # Posts / Categories / Tags in sidebar.
  site_state: true

  # Social Links.
  # Usage: `Key: permalink || icon`
  # Key is the link label showing to end users.
  # Value before `||` delimeter is the target permalink.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, globe icon will be loaded.
  social:
    GitHub: https://github.com/MoonBegonia || github
    #E-Mail: mailto:yourname@gmail.com || envelope
    #Google: https://plus.google.com/yourname || google
    #Twitter: https://twitter.com/yourname || twitter
    #FB Page: https://www.facebook.com/yourname || facebook
    #VK Group: https://vk.com/yourname || vk
    #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
    #YouTube: https://youtube.com/yourname || youtube
    #Instagram: https://instagram.com/yourname || instagram
    #Skype: skype:yourname?call|chat || skype
    Telegram: https://t.me/MoonBegonia || telegram

  social_icons:
    enable: true
    icons_only: false
    transition: false
    # Dependencies: exturl: true in Tags Settings section below.
    # To encrypt links above use https://www.base64encode.org
    # Example encoded link: `GitHub: aHR0cHM6Ly9naXRodWIuY29tL3RoZW1lLW5leHQ= || github`
    exturl: false

  # Follow me on GitHub banner in right-top corner.
  # Usage: `permalink || title`
  # Value before `||` delimeter is the target permalink.
  # Value after `||` delimeter is the title and aria-label name.
  #github_banner: https://github.com/yourname || Follow me on GitHub

  # Blog rolls
  links_icon: link
  links_title: Links
  links_layout: block
  #links_layout: inline
  #links:
    #Title: http://example.com/

    # Sidebar Avatar
  avatar:
    # in theme directory(source/images): /images/avatar.gif
    # in site  directory(source/uploads): /uploads/avatar.gif
    # You can also use other linking images.
    url: https://blog-1253491707.piccd.myqcloud.com/avatar1.jpg #/images/avatar.gif
    # If true, the avatar would be dispalyed in circle.
    rounded: true
    # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
    opacity: 1
    # If true, the avatar would be rotated with the cursor.
    rotated: false

  # Table Of Contents in the Sidebar
  toc:
    enable: true

    # Automatically add list number to toc.
    number: true

    # If true, all words will placed on next lines if header width longer then sidebar width.
    wrap: false

  sidebar:
    # Sidebar Position, available value: left | right (only for Pisces | Gemini).
    position: left
    #position: right

    # Manual define the sidebar width.
    # If commented, will be default for:
    # Muse | Mist: 320
    # Pisces | Gemini: 240
    #width: 300

    # Sidebar Display, available value (only for Muse | Mist):
    #  - post    expand on posts automatically. Default.
    #  - always  expand for all pages automatically
    #  - hide    expand only when click on the sidebar toggle icon.
    #  - remove  Totally remove sidebar including sidebar toggle.
    display: post
    #display: always
    #display: hide
    #display: remove

    # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
    offset: 12

    # Back to top in sidebar (only for Pisces | Gemini).
    b2t: true

    # Scroll percent label in b2t button.
    scrollpercent: true

    # Enable sidebar on narrow view (only for Muse | Mist).
    onmobile: false

  # ---------------------------------------------------------------
  # Post Settings
  # ---------------------------------------------------------------

  # Automatically scroll page to section which is under <!-- more --> mark.
  scroll_to_more: true

  # Automatically saving scroll position on each post/page in cookies.
  save_scroll: false

  # Automatically excerpt description in homepage as preamble text.
  excerpt_description: true

  # Automatically Excerpt. Not recommend.
  # Please use <!-- more --> in the post to control excerpt accurately.
  auto_excerpt:
    enable: false
    length: 150

  # 文章末尾添加“本文结束”标记
  passage_end_tag:
    enabled: true

  # Post meta display settings
  post_meta:
    item_text: true
    created_at: true
    updated_at:
      enabled: true
      # If true, show updated date label only if `updated date` different from 'created date' (post edited in another day than was created).
      # And if post will edited in same day as created, edited time will show in popup title under created time label.
      # If false show anyway, but if post edited in same day, show only edited time.
      another_day: true
    categories: true

  #字数统计及阅读时长
  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: false
    awl: 2
    wpm: 200

  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright
  # https://github.com/chriskempson/tomorrow-theme
  highlight_theme: normal

  # Enable "cheers" for archive page.
  cheers_enabled: true

  codeblock:
    # Manual define the border radius in codeblock
    # Leave it empty for the default 1
    border_radius:
    # Add copy button on codeblock
    copy_button:
      enable: true
      # Show text copy result
      show_result: true

  # Wechat Subscriber
  #wechat_subscriber:
    #enabled: true
    #qcode: /path/to/your/wechatqcode ex. /uploads/wechat-qcode.jpg
    #description: ex. subscribe to my blog by scanning my public wechat account

  # Reward
  #reward_comment: Donate comment here
  #wechatpay: /images/wechatpay.jpg
  #alipay: /images/alipay.jpg
  #bitcoin: /images/bitcoin.png

  # Related popular posts
  # Dependencies: https://github.com/tea3/hexo-related-popular-posts
  related_posts:
    enable: false
    title: # custom header, leave empty to use the default one
    display_in_home: false
    params:
      maxCount: 5
      #PPMixingRate: 0.0
      #isDate: false
      #isImage: false
      #isExcerpt: false

  # Post edit
  # Dependencies: https://github.com/hexojs/hexo-deployer-git
  post_edit:
    enable: false
    url: https://github.com/theme-next/theme-next.org/_posts/tree/master/ # Link for view source.
  # url: https://github.com/theme-next/theme-next.org/_posts/edit/master/ # Link for fork & edit.

  # ---------------------------------------------------------------
  # Font Settings
  # ---------------------------------------------------------------

  font:
    enable: false

    # Uri of fonts host. E.g. //fonts.googleapis.com (Default).
    host:

    # Font options:
    # `external: true` will load this font family from `host` above.
    # `family: Times New Roman`. Without any quotes.
    # `size: xx`. Use `px` as unit.

    # Global font settings used for all elements in <body>.
    global:
      external: true
      family: Lato
      size: 15

    # Font settings for Headlines (H1, H2, H3, H4, H5, H6).
    # Fallback to `global` font settings.
    headings:
      external: true
      family:
      size: 

    # Font settings for posts.
    # Fallback to `global` font settings.
    posts:
      external: true
      family: 

    # Font settings for Logo.
    # Fallback to `global` font settings.
    logo:
      external: true
      family:
      size:

    # Font settings for <code> and code blocks.
    codes:
      external: true
      family: Consolas
      size: 15

  # ---------------------------------------------------------------
  # Third Party Services Settings
  # ---------------------------------------------------------------

  #鼠标特效
  fireworks: false
  love: true

  #动态背景
  # Canvas-nest
  # Dependencies: https://github.com/theme-next/theme-next-canvas-nest
  canvas_nest:
    enable: true
    onmobile: true # display on mobile or not
    color: '0,0,255' # RGB values, use ',' to separate
    opacity: 0.6 # the opacity of line: 0~1
    zIndex: -1 # z-index property of the background
    count: 120 # the number of lines

  # JavaScript 3D library.
  # Dependencies: https://github.com/theme-next/theme-next-three
  # three_waves
  three_waves: false
  canvas_lines: false
  canvas_sphere: false

  # Only fit scheme Pisces
  # Dependencies: https://github.com/theme-next/theme-next-canvas-ribbon
  # Canvas-ribbon
  # size: The width of the ribbon.
  # alpha: The transparency of the ribbon.
  # zIndex: The display level of the ribbon.
  canvas_ribbon:
    enable: false
    size: 300
    alpha: 0.6
    zIndex: -1

  # Han Support
  # Dependencies: https://github.com/theme-next/theme-next-han
  han: false

  # Pangu Support
  # Dependencies: https://github.com/theme-next/theme-next-pangu
  # For more information: https://github.com/vinta/pangu.js
  pangu: true

  local_search:
    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # unescape html strings to the readable one
    unescape: false

  # Support for gitalk comments system.
  gitalk:
    enable: false
    clientID: fcdb896a42ee148bcebe
    clientSecret: 55fa144a2a8c3ce9a7462d16825d94d5914ec59a
    repo: Gitalk
    owner: MoonBegonia
    admin: MoonBegonia

  # Show number of visitors to each article.
  # You can visit https://leancloud.cn get AppID and AppKey.
  leancloud_visitors:
    enable: false
    app_id: gd0SoNU3oi1VuQnmWS0Jlo8f-gzGzoHsz
    app_key: BslzzEx6GBoQN1vvaR8khtzJ
    # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
    # If you don't care about security in lc counter and just want to use it directly
    # (without hexo-leancloud-counter-security plugin), set the `security` to `false`.
    security: false
    betterPerformance: false

  valine:
    enable: true
    appid:  gd0SoNU3oi1VuQnmWS0Jlo8f-gzGzoHsz
    appkey:  BslzzEx6GBoQN1vvaR8khtzJ
    notify: true # mail notifier , https://github.com/xCss/Valine/wiki
    verify: true # Verification code
    placeholder: ヾﾉ≧∀≦)o来啊，快活啊!
    avatar: wavatar # gravatar style
    guest_info: nick,mail,link # custom comment header
    pageSize: 10 # pagination size
    visitor: true # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html

  # ---------------------------------------------------------------
  # Tags Settings
  # ---------------------------------------------------------------

  # Note tag (bs-callout).
  note:
    # Note tag style values:
    #  - simple    bs-callout old alert style. Default.
    #  - modern    bs-callout new (v2-v3) alert style.
    #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
    #  - disabled  disable all CSS styles import of note tag.
    style: simple
    icons: false
    border_radius: 3
    # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
    # Offset also applied to label tag variables. This option can work with disabled note tag.
    light_bg_offset: 0

  # Label tag.
  label: true

  # Tabs tag.
  tabs:
    enable: true
    transition:
      tabs: false
      labels: true
    border_radius: 0

  # Reading progress bar
  # Dependencies: https://github.com/theme-next/theme-next-reading-progress
  reading_progress:
    enable: false
    color: "#37c6c0"
    height: 2px

  # Google Webmaster tools verification setting
  # See: https://www.google.com/webmasters/
  google_site_verification: uGBNF83sgg7uZTxWsvqWZyQp6PswDH1uBfIYuC13LLw

  # Baidu Webmaster tools verification setting
  # See: https://ziyuan.baidu.com/site
  baidu_site_verification: WOmbfKoQ7x

  # Google Analytics
  google_analytics: UA-119354100-2