name: deploy to oss

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the hexo branch (change to your hexo blog branch)
on:
  push:
    branches: [hexo]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hexo-deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          submodules: true

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Change post files modified time
        run: |
          find source/_posts -name '*.md' | while read file
          do touch -d "$(git log -1 --format="@%ct" "$file")" "$file"
          done

      - name: hexo generate
        run: |
          npm install yarn -g
          export PATH="$PATH:`yarn global bin`"
          yarn global add hexo-cli
          yarn
          hexo clean
          hexo g

      - name: deploy public/css to cos
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.COS_KEY_ID }}
          secret_key: ${{ secrets.COS_KEY_SECERT }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: public/css
          remote_path: next/css

      - name: deploy public/js to cos
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.COS_KEY_ID }}
          secret_key: ${{ secrets.COS_KEY_SECERT }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: public/js
          remote_path: next/js

      - name: deploy public/images to cos
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.COS_KEY_ID }}
          secret_key: ${{ secrets.COS_KEY_SECERT }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: public/images
          remote_path: next/images

      - name: setup oss util
        uses: manyuanrong/setup-ossutil@v1.0
        with:
          endpoint: '${{ secrets.OSS_ENDPOINT }}'
          access-key-id: '${{ secrets.OSS_KEY_ID }}'
          access-key-secret: '${{ secrets.OSS_KEY_SECRET }}'

      - name: clean bucket
        run: ossutil rm oss://${{ secrets.OSS_BUCKET }}/ -rf

      - name: deploy to oss
        run: ossutil cp public/ oss://${{ secrets.OSS_BUCKET }}/ -rf

      - name: notification
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.TG_BOT_TOKEN }}
          chatId: ${{ secrets.TG_CHAT_ID }}
          jobStatus: ${{ job.status }}
          skipSuccess: false
